id: P010383
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-19 20:47:00.360335
source_metadata:
  id: bdr:W27484
  title: ནུབ་རི་དང་སྐུ་ཐང་གི་བླ་མའི་རྣམ་ཐར
  author: ''
  volumes:
    113b210b0e784a819dafd74a752b096e:
      image_group_id: I2DB64724
      title: ''
      volume_number: 1
      total_pages: 806
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
